import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.arenapulse.mobile',
  appName: 'TournArena',
  webDir: '../../dist/mobile/browser',
  // The native CapacitorHttp plugin is enabled by default and intercepts
  // fetch()/XMLHttpRequest, routing them through Android's native HTTP
  // client instead of the WebView. That native client enforces Android's
  // cleartext-traffic policy (blocked by default on API 28+), and
  // android:usesCleartextTraffic="true" is never written to
  // AndroidManifest.xml (apps/mobile/android is gitignored/regenerated by
  // `cap sync`, and this repo's config never sets it) -- only the initial
  // page load honors capacitor.config's own `cleartext`/`server.url`
  // (set directly by the Bridge). Net effect on the local emulator: the app
  // opens fine (the page itself loads) but every API call silently fails,
  // with nothing in the WebView/Chromium console since the request never
  // reaches it. Disabling CapacitorHttp routes fetch/XHR through the
  // WebView instead, which already handles this correctly (see
  // infra/scripts/run-mobile-emulator.mjs's own cleartext/CORS_ORIGIN
  // handling for local dev). Production is HTTPS-only and unaffected.
  plugins: {
    CapacitorHttp: { enabled: false },
  },
};

export default config;
